name: task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  google_fonts: 2.2.0
  provider: ^6.0.1
  cherry_toast: ^1.0.4
  shared_preferences: ^2.0.13
  connectivity: ^3.0.3
  dotted_border: ^2.0.0+2
  pin_code_fields: ^7.4.0
  cached_network_image: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true



  assets:
    - assets/images/
